const names = 
[{
    "id": 1,
    "first_name": "Walden",
    "last_name": "Bridewell",
    "email": "wbridewell0@nytimes.com",
    "gender": "Male"
  }, {
    "id": 2,
    "first_name": "Yank",
    "last_name": "Brandino",
    "email": "ybrandino1@cornell.edu",
    "gender": "Male"
  }, {
    "id": 3,
    "first_name": "Chantal",
    "last_name": "Brockie",
    "email": "cbrockie2@slideshare.net",
    "gender": "Female"
  }, {
    "id": 4,
    "first_name": "Guglielma",
    "last_name": "Isbell",
    "email": "gisbell3@miibeian.gov.cn",
    "gender": "Female"
  }, {
    "id": 5,
    "first_name": "Neils",
    "last_name": "Phethean",
    "email": "nphethean4@4shared.com",
    "gender": "Male"
  }, {
    "id": 6,
    "first_name": "Paige",
    "last_name": "Allport",
    "email": "pallport5@businessinsider.com",
    "gender": "Female"
  }, {
    "id": 7,
    "first_name": "Deborah",
    "last_name": "Verrell",
    "email": "dverrell6@google.fr",
    "gender": "Female"
  }, {
    "id": 8,
    "first_name": "Aylmer",
    "last_name": "Hovert",
    "email": "ahovert7@shareasale.com",
    "gender": "Male"
  }, {
    "id": 9,
    "first_name": "Monah",
    "last_name": "Whittlesea",
    "email": "mwhittlesea8@mozilla.com",
    "gender": "Female"
  }, {
    "id": 10,
    "first_name": "Deirdre",
    "last_name": "Francesc",
    "email": "dfrancesc9@amazon.co.uk",
    "gender": "Female"
  }, {
    "id": 11,
    "first_name": "Austin",
    "last_name": "Balling",
    "email": "aballinga@psu.edu",
    "gender": "Male"
  }, {
    "id": 12,
    "first_name": "Gerry",
    "last_name": "Greasty",
    "email": "ggreastyb@ameblo.jp",
    "gender": "Male"
  }, {
    "id": 13,
    "first_name": "Cybil",
    "last_name": "Chamberlayne",
    "email": "cchamberlaynec@archive.org",
    "gender": "Female"
  }, {
    "id": 14,
    "first_name": "Madelon",
    "last_name": "Mandeville",
    "email": "mmandevilled@storify.com",
    "gender": "Female"
  }, {
    "id": 15,
    "first_name": "Ezri",
    "last_name": "Jaquin",
    "email": "ejaquine@arizona.edu",
    "gender": "Male"
  }, {
    "id": 16,
    "first_name": "Leopold",
    "last_name": "Karppi",
    "email": "lkarppif@miibeian.gov.cn",
    "gender": "Male"
  }, {
    "id": 17,
    "first_name": "Derry",
    "last_name": "Zuann",
    "email": "dzuanng@bandcamp.com",
    "gender": "Male"
  }, {
    "id": 18,
    "first_name": "Dorree",
    "last_name": "Strethill",
    "email": "dstrethillh@nyu.edu",
    "gender": "Female"
  }, {
    "id": 19,
    "first_name": "Avigdor",
    "last_name": "Huet",
    "email": "ahueti@fastcompany.com",
    "gender": "Male"
  }, {
    "id": 20,
    "first_name": "Silvie",
    "last_name": "Stockney",
    "email": "sstockneyj@weebly.com",
    "gender": "Female"
  }, {
    "id": 21,
    "first_name": "Fleming",
    "last_name": "Megson",
    "email": "fmegsonk@sina.com.cn",
    "gender": "Male"
  }, {
    "id": 22,
    "first_name": "Kenon",
    "last_name": "Smyth",
    "email": "ksmythl@tuttocitta.it",
    "gender": "Male"
  }, {
    "id": 23,
    "first_name": "Pablo",
    "last_name": "Savoury",
    "email": "psavourym@kickstarter.com",
    "gender": "Male"
  }, {
    "id": 24,
    "first_name": "Lukas",
    "last_name": "Adger",
    "email": "ladgern@princeton.edu",
    "gender": "Male"
  }, {
    "id": 25,
    "first_name": "Thane",
    "last_name": "Iorns",
    "email": "tiornso@wunderground.com",
    "gender": "Male"
  }]

  export default names;